name: PerfectFishing
version: 1.2.0
main: pl.bfscode.perfectfishing.PerfectFishingPlugin
api-version: '1.20'
softdepend:
  - EvenMoreFish
  - PlaceholderAPI
commands:
  perfectfishing:
    description: PerfectFishing admin command
    usage: /perfectfishing reload
    aliases:
      - pfishing
      - pfish
permissions:
  perfectfishing.admin:
    default: op
  perfectfishing.alerts:
    description: Otrzymuje alerty o podejrzeniu automatu na ryby.
    default: op
